// Auto-generated by HelliParse-1.5

// Edit only if you know what you're doing!

// % this is the comment!
#ifndef X
#define X "SomeSettings"
#endif


#ifndef Y
#define Y 3
#endif


#ifndef Z
#define Z DEFAULt
#endif


