// Auto-generated by HelliParse-1.5

// Edit only if you know what you're doing!

#define DEFAULT XCB_NONE

// % this is the comment!
#ifndef MOD
#define MOD XCB_MOD_MASK_4
#endif


#ifndef BG
#define BG 3
#endif


#ifndef BBG
#define BBG DEFAULT
#endif


#ifndef TC
#define TC DEFAULT
#endif


#ifndef QK
#define QK DEFAULT
#endif


#ifndef LK
#define LK DEFAULT
#endif


#ifndef CK
#define CK XK_C
#endif


