// Auto-generated by HelliParse-1.5

// Edit only if you know what you're doing!

#define DEFAULT XCB_NONE

// % this is the comment!
#ifndef mod
#define mod XCB_MOD_MASK_4
#endif


#ifndef bg
#define bg 3
#endif


#ifndef bbg
#define bbg DEFAULT
#endif


#ifndef tc
#define tc DEFAULT
#endif


#ifndef QK
#define QK DEFAULT
#endif


#ifndef LK
#define LK DEFAULT
#endif


#ifndef CK
#define CK XK_C
#endif


