// Auto-generated by HelliParse-1.5

// Edit only if you know what you're doing!

#define DEFAULT XCB_NONE

// % this is the comment!
#ifndef MOD
#define MOD XCB_MOD_MASK_4
#endif


#ifndef BG
#define BG DEFAULT
#endif


#ifndef BBG
#define BBG 0x000000
#endif


#ifndef TC
#define TC DEFAULT
#endif


#ifndef QK
#define QK XK_D
#endif


#ifndef LK
#define LK DEFAULT
#endif


#ifndef CK
#define CK XK_Escape
#endif


